/* ArcticM
 * Author: ssa
 * Creation date: 7/26/2018
 */
MACHINE
    ArcticM

OPERATIONS
	insertIntoVehicleESIMFromShip = 
	skip;

	insertIntoVesselESIMFromShip = 
	skip;

	insertIntoVehicleVICTFromShipPositions = 
	skip;

	insertIntoVesselVICTFromShipPositions = 
	skip;

	createVehicleLink = 
	skip;

	insertIntoVehicleFromVehicleVICTVehicleESIMVehicleLink = 
	skip;

	insertIntoVesselFromVesselVICTVesselESIMVehicleLink = 
	skip


END
