-- database generated with pgmodeler (postgresql database modeler).
-- pgmodeler  version: 0.9.3
-- postgresql version: 13.0
-- project site: pgmodeler.io
-- model author: ---
-- object: cmp | type: role --
-- drop role if exists cmp;
-- create role cmp with ;
-- ddl-end --


-- database creation must be performed outside a multi lined sql file. 
-- these commands were put in this file only as a convenience.
-- 
-- object: smart_landuse_db | type: database --
-- drop database if exists smart_landuse_db;
-- create database smart_landuse_db;
-- ddl-end --


-- object: data | type: schema --
-- drop schema if exists data cascade;
create schema data;
-- ddl-end --
alter schema data owner to cmp;
-- ddl-end --


-- object: agroecological_group_registry."ae_type" | type: table --
-- drop table if exists agroecological_group_registry."ae_type" cascade;
create table agroecological_group_registry."ae_type" (
	ae_type_id bigint not null generated by default as identity ,
	ae_group_id bigint,
	name varchar,
	relief varchar,
	otlozheniya varchar,
	pochva varchar,
	climate varchar,
	constraint "ae_soil_type_pk" primary key (ae_type_id)

);
-- ddl-end --
comment on table agroecological_group_registry."ae_type" is e'агроэкологический вид земель';
-- ddl-end --
comment on column agroecological_group_registry."ae_type".name is e'название агроэкологического вида земель';
-- ddl-end --
comment on column agroecological_group_registry."ae_type".relief is e'рельеф';
-- ddl-end --
comment on column agroecological_group_registry."ae_type".otlozheniya is e'отложения';
-- ddl-end --
comment on column agroecological_group_registry."ae_type".pochva is e'почва';
-- ddl-end --
comment on column agroecological_group_registry."ae_type".climate is e'климат';
-- ddl-end --
alter table agroecological_group_registry."ae_type" owner to cmp;
-- ddl-end --


-- object: agroecological_group_registry."ae_group" | type: table --
-- drop table if exists agroecological_group_registry."ae_group" cascade;
create table agroecological_group_registry."ae_group" (
	ae_group_id bigint not null generated by default as identity ,
	name varchar,
	description varchar,
	constraint "ae_soil_group_pk" primary key (ae_group_id)

);
-- ddl-end --
comment on table agroecological_group_registry."ae_group" is e'агроэкологическая группа земель';
-- ddl-end --
comment on column agroecological_group_registry."ae_group".name is e'название агроэкологической группы земель';
-- ddl-end --
comment on column agroecological_group_registry."ae_group".description is e'описание';
-- ddl-end --
alter table agroecological_group_registry."ae_group" owner to cmp;
-- ddl-end --

-- object: agroecological_group_registry."province" | type: table --
-- drop table if exists agroecological_group_registry."province" cascade;
create table agroecological_group_registry."province" (
	province_id bigint not null generated by default as identity ,
	zone_id bigint,
	name varchar,
	geomorphology varchar,
	climate varchar,
	constraint "province_pk" primary key (province_id)

);
-- ddl-end --
comment on table agroecological_group_registry."province" is e'провинция';
-- ddl-end --
comment on column agroecological_group_registry."province".name is e'название провинции';
-- ddl-end --
comment on column agroecological_group_registry."province".geomorphology is e'геоморфология';
-- ddl-end --
comment on column agroecological_group_registry."province".climate is e'климат';
-- ddl-end --
alter table agroecological_group_registry."province" owner to cmp;
-- ddl-end --

-- object: agroecological_group_registry."zone" | type: table --
-- drop table if exists agroecological_group_registry."zone" cascade;
create table agroecological_group_registry."zone" (
	zone_id bigint not null generated by default as identity ,
	name varchar,
	constraint "zone_pk" primary key (zone_id)

);
-- ddl-end --
comment on table agroecological_group_registry."zone" is e'зона';
-- ddl-end --
comment on column agroecological_group_registry."zone".name is e'название зоны';
-- ddl-end --
alter table agroecological_group_registry."zone" owner to cmp;
-- ddl-end --

-- object: agroecological_group_registry."region" | type: table --
-- drop table if exists agroecological_group_registry."region" cascade;
create table agroecological_group_registry."region" (
	region_id bigint not null generated by default as identity ,
	province_id bigint,
	name varchar,
	constraint "region_pk" primary key (region_id)

);
-- ddl-end --
comment on table agroecological_group_registry."region" is e'округ';
-- ddl-end --
comment on column agroecological_group_registry."region".name is e'название округа';
-- ddl-end --
alter table agroecological_group_registry."region" owner to cmp;
-- ddl-end --

-- object: agroecological_group_registry."administrative_district" | type: table --
-- drop table if exists agroecological_group_registry."administrative_district" cascade;
create table agroecological_group_registry."administrative_district" (
	administrative_district_id bigint not null generated by default as identity ,
	administrative_region_id bigint,
	name varchar,
	constraint "administrative_district_pk_cp" primary key (administrative_district_id)

);
-- ddl-end --
comment on table agroecological_group_registry."administrative_district" is e'район области';
-- ddl-end --
comment on column agroecological_group_registry."administrative_district".administrative_region_id is e'название области';
-- ddl-end --
comment on column agroecological_group_registry."administrative_district".name is e'название района';
-- ddl-end --
alter table agroecological_group_registry."administrative_district" owner to cmp;
-- ddl-end --

-- object: agroecological_group_registry."administrative_region" | type: table --
-- drop table if exists agroecological_group_registry."administrative_region" cascade;
create table agroecological_group_registry."administrative_region" (
	administrative_region_id bigint not null generated by default as identity ,
	name varchar,
	constraint "administrative_region_pk_cp" primary key (administrative_region_id)

);
-- ddl-end --
comment on table agroecological_group_registry."administrative_region" is e'область';
-- ddl-end --
comment on column agroecological_group_registry."administrative_region".name is e'название области';
-- ddl-end --
alter table agroecological_group_registry."administrative_region" owner to cmp;
-- ddl-end --


-- object: agroecological_group_registry."province_ae_type" | type: table --
-- drop table if exists agroecological_group_registry."province_ae_type" cascade;
create table agroecological_group_registry."province_ae_type" (
	province_id bigint,
	ae_type_id bigint
);
-- ddl-end --
alter table agroecological_group_registry."province_ae_type" owner to cmp;
-- ddl-end --

-- object: agroecological_group_registry."administrative_region_zone" | type: table --
-- drop table if exists agroecological_group_registry."administrative_region_zone" cascade;
create table agroecological_group_registry."administrative_region_zone" (
	administrative_region_id bigint not null,
	zone_id bigint not null,
	constraint "administrative_region_zone_pk" primary key (administrative_region_id,zone_id)

);
-- ddl-end --
alter table agroecological_group_registry."administrative_region_zone" owner to cmp;
-- ddl-end --

-- object: agroecological_group_registry."administrative_district_province" | type: table --
-- drop table if exists agroecological_group_registry."administrative_district_province" cascade;
create table agroecological_group_registry."administrative_district_province" (
	administrative_district_id bigint not null,
	province_id bigint not null,
	constraint "administrative_district_province_pk" primary key (administrative_district_id,province_id)

);
-- ddl-end --
alter table agroecological_group_registry."administrative_district_province" owner to cmp;
-- ddl-end --

-- object: agroecological_group_registry."ae_type_property" | type: table --
-- drop table if exists agroecological_group_registry."ae_type_property" cascade;
create table agroecological_group_registry."ae_type_property" (
	ae_type_id bigint not null generated by default as identity ,
	name varchar not null,
	units varchar,
	value varchar,
	constraint "ae_type_property_pk" primary key (ae_type_id,name)

);
-- ddl-end --
comment on table agroecological_group_registry."ae_type_property" is e'свойства видов земель';
-- ddl-end --
comment on column agroecological_group_registry."ae_type_property".name is e'названние свойства';
-- ddl-end --
comment on column agroecological_group_registry."ae_type_property".units is e'единица измерения';
-- ddl-end --
comment on column agroecological_group_registry."ae_type_property".value is e'значение своства';
-- ddl-end --
alter table agroecological_group_registry."ae_type_property" owner to cmp;
-- ddl-end --

